app = 'mcphubx'
primary_region = 'sin'

[env]
  AUTH_PASSWORD = { from_secret = "AUTH_PASSWORD" }
  PERPLEXITY_API_KEY = { from_secret = "PERPLEXITY_API_KEY" }

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = "mcphub"
  destination = "/app/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
